remove working_directory

diff --git a/.github/workflows/e2e-demo.yml b/.github/workflows/e2e-demo.yml
--- a/.github/workflows/e2e-demo.yml
+++ b/.github/workflows/e2e-demo.yml
@@ -37,25 +37,25 @@ jobs:
           password: ${{ secrets.DOCKER_PASS }}
           logout: true
 
-      - name: Build docker images
-        run: |
-          # Fails the build if anything returns non-zero
-          set -e
-          # Echo commands to the console
-          set -x
+      # - name: Build docker images
+      #   run: |
+      #     # Fails the build if anything returns non-zero
+      #     set -e
+      #     # Echo commands to the console
+      #     set -x
 
-          # Build backend and frontend images
-          cd backend
-          docker build -t ${{ secrets.DOCKER_URL }}/burger-back:${{ github.sha }} .
-          cd ../frontend
-          docker build -t ${{ secrets.DOCKER_URL }}/burger-front:${{ github.sha }} .
-          cd ../
+      #     # Build backend and frontend images
+      #     cd backend
+      #     docker build -t ${{ secrets.DOCKER_URL }}/burger-back:${{ github.sha }} .
+      #     cd ../frontend
+      #     docker build -t ${{ secrets.DOCKER_URL }}/burger-front:${{ github.sha }} .
+      #     cd ../
 
-      - name: Push Docker Images
-        run: |
-          # push docker images to dockerhub
-          docker push ${{ secrets.DOCKER_URL }}/burger-back:${{ github.sha }}
-          docker push ${{ secrets.DOCKER_URL }}/burger-front:${{ github.sha }}
+      # - name: Push Docker Images
+      #   run: |
+      #     # push docker images to dockerhub
+      #     docker push ${{ secrets.DOCKER_URL }}/burger-back:${{ github.sha }}
+      #     docker push ${{ secrets.DOCKER_URL }}/burger-front:${{ github.sha }}
 
       - name: Checkout config manifests
         uses: actions/checkout@v3
@@ -68,16 +68,16 @@ jobs:
           # Alter k8s.yaml to sed the version
           sed -i'' -e 's/DOCKER_URL/${{ secrets.DOCKER_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' -e 's/FRONTEND_URL/${{ vars.FRONTEND_URL }}/g' config-repo/k8s.yaml
 
-          # Install ngrok ingress controller
-          helm repo add ngrok https://charts.ngrok.com
-          helm install ngrok-operator ngrok/ngrok-operator \
-            --namespace burgers \
-            --create-namespace \
-            --set credentials.apiKey=${{ secrets.NGROK_API_KEY }} \
-            --set credentials.authtoken=${{ secrets.NGROK_AUTHTOKEN }}
+          # # Install ngrok ingress controller
+          # helm repo add ngrok https://charts.ngrok.com
+          # helm install ngrok-operator ngrok/ngrok-operator \
+          #   --namespace burgers \
+          #   --create-namespace \
+          #   --set credentials.apiKey=${{ secrets.NGROK_API_KEY }} \
+          #   --set credentials.authtoken=${{ secrets.NGROK_AUTHTOKEN }}
 
-          # Run containers in k3s
-          kubectl apply -f config-repo/k8s.yaml
+          # # Run containers in k3s
+          # kubectl apply -f config-repo/k8s.yaml
 
       # - name: Setup upterm session
       #   uses: lhotari/action-upterm@v1
@@ -100,9 +100,9 @@ jobs:
         run: |
           git add config-repo/k8s.yaml
           git commit -m "Updating k8s manifest"
-        working-directory: ./
+        # working-directory: ./
 
       - name: Push changes to config-repo
         run: |
           git push -u origin HEAD:render_prod
-        working-directory: ./        
+        # working-directory: ./        
